/*
SQLyog Community v13.2.1 (64 bit)
MySQL - 8.1.0 : Database - nacos
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`nacos` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `nacos`;

/*Table structure for table `config_info` */

DROP TABLE IF EXISTS `config_info`;

CREATE TABLE `config_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `content` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8mb3 COLLATE utf8mb3_bin COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfo_datagrouptenant` (`data_id`,`group_id`,`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=86 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin COMMENT='config_info';

/*Data for the table `config_info` */

insert  into `config_info`(`id`,`data_id`,`group_id`,`content`,`md5`,`gmt_create`,`gmt_modified`,`src_user`,`src_ip`,`app_name`,`tenant_id`,`c_desc`,`c_use`,`effect`,`type`,`c_schema`) values 
(2,'common.yaml','DEFAULT_GROUP','server:\n  servlet:\n    session:\n      cookie:\n        name: GULISESSION\n        domain: renchao05.top\n\nspring:\n  cloud:\n    sentinel:\n      transport:\n        dashboard: sentinel:8080\n        port: 8719\n\n  zipkin:\n    base-url: http://zipkin:9411/\n    discoveryClientEnabled: false\n    sender:\n      type: web\n  sleuth:\n    sampler:\n      #采样率值介于 0 到 1 之间，1 则表示全部采集\n      probability: 1.0\n\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n\n  mvc:\n    date-format: yyyy-MM-dd HH:mm:ss\n\n\n  redis:\n    host: redis\n    password: mall@111111\n  # RabbitMQ 配置，其他的配置都有默认值\n  rabbitmq:\n    host: rabbitmq\n    username: mall\n    password: mall@111111\n    \n  # 配置缓存类型\n  cache:\n    type: redis\n    redis:\n      time-to-live: 360000\n      # 缓存空值\n      cache-null-values: true\n  # 分布式session配置\n  session:\n    store-type: redis\n\n\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n\nfeign:\n  sentinel:\n    enabled: true\n\n\nseata:\n  tx-service-group: default_tx_group\n  service:\n    vgroup-mapping:\n      default_tx_group: default\n  config:\n    type: nacos\n    nacos:\n      server-addr: nacos:8848\n      group : \"SEATA_GROUP\"\n      namespace: \"6a8ee0cb-25fa-42ea-8336-1c62a88751af\"\n      dataId: \"seataServer.properties\"\n  registry:\n    type: nacos\n    nacos:\n      application: seata-server\n      server-addr: nacos:8848\n      group : \"SEATA_GROUP\"\n      namespace: \"6a8ee0cb-25fa-42ea-8336-1c62a88751af\"\n','c9acaeabf2602a06fc3c793a5ca3b264','2022-09-08 13:18:09','2023-12-27 12:40:13','nacos','10.0.0.86','','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b','','','','yaml',''),
(3,'mall-gateway-prod.yaml','DEFAULT_GROUP','spring:\n  cloud:\n    gateway:\n      routes:\n        - id: product_routh\n          uri: lb://mall-product\n          predicates:\n            - Path=/api/product/**\n          filters:\n            - RewritePath=/api/product(?<segment>/?.*), /product$\\{segment}\n\n        - id: member_routh\n          uri: lb://mall-member\n          predicates:\n            - Path=/api/member/**\n          filters:\n            - RewritePath=/api/member(?<segment>/?.*), /member$\\{segment}\n\n        - id: coupon_routh\n          uri: lb://mall-coupon\n          predicates:\n            - Path=/api/coupon/**\n          filters:\n            - RewritePath=/api/coupon(?<segment>/?.*), /coupon$\\{segment}\n\n        - id: ware_routh\n          uri: lb://mall-ware\n          predicates:\n            - Path=/api/ware/**\n          filters:\n            - RewritePath=/api/ware(?<segment>/?.*), /ware$\\{segment}\n\n        - id: third_party_routh\n          uri: lb://mall-third-party\n          predicates:\n            - Path=/api/thirdparty/**\n          filters:\n            - RewritePath=/api/thirdparty(?<segment>/?.*), $\\{segment}\n\n        - id: admin_routh\n          uri: lb://mall-admin\n          predicates:\n            - Path=/api/**\n          filters:\n            - RewritePath=/api(?<segment>/?.*), /renren-fast$\\{segment}\n\n        - id: mall_host_routh\n          uri: lb://mall-product\n          predicates:\n            - Host=renchao05.top,item.renchao05.top\n\n\n        - id: search_routh\n          uri: lb://mall-search\n          predicates:\n            - Host=search.renchao05.top\n\n        - id: auth_routh\n          uri: lb://mall-auth-server\n          predicates:\n            - Host=auth.renchao05.top\n\n        - id: cart_routh\n          uri: lb://mall-cart\n          predicates:\n            - Host=cart.renchao05.top\n\n        - id: order_routh\n          uri: lb://mall-order\n          predicates:\n            - Host=order.renchao05.top\n\n        - id: member_routh\n          uri: lb://mall-member\n          predicates:\n            - Host=member.renchao05.top\n\n        - id: seckill_routh\n          uri: lb://mall-seckill\n          predicates:\n            - Host=seckill.renchao05.top\n\n        - id: admin_fast_routh\n          uri: lb://renren-fast\n          predicates:\n            - Host=admin.renchao05.top','e2afeaad540a0d969ed4f9544929225e','2022-09-08 13:25:28','2023-12-28 23:24:25','nacos','10.0.0.86','','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b','','','','yaml',''),
(5,'mall-product-prod.yaml','DEFAULT_GROUP','spring:\n  application:\n    name: mall-product\n\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n#      logic-delete-field: showStatus\n      logic-delete-value: 0\n      logic-not-delete-value: 1\n\n#logging:\n#  level:\n#    com.renchao.mall.product.dao: debug\n\nmall:\n  thread:\n    core-size: 20\n    max-size: 100\n    keep-alive-time: 10','0bda7c65ad46f2f56a1414897d303a9c','2022-09-09 00:53:02','2023-12-27 00:11:30','nacos','10.0.0.86','','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b','','','','yaml',''),
(9,'mall-ware-prod.yaml','DEFAULT_GROUP','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto','90fc1d01fff0918f5dd817cfee0caf9a','2022-09-09 03:25:43','2023-12-26 23:57:19','nacos','10.0.0.86','','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b','','','','yaml',''),
(12,'mall-auth-server-prod.yaml','DEFAULT_GROUP','# ','1c59d20c34b0a3c9b1b21b85ccda9dce','2022-09-09 05:36:15','2022-09-09 05:36:15',NULL,'183.209.92.80','','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b',NULL,NULL,NULL,'yaml',NULL),
(14,'mall-coupon-prod.yaml','DEFAULT_GROUP','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto','b24b8041edf565ad976aee32c20b6258','2022-09-09 09:08:50','2023-12-27 00:12:18','nacos','10.0.0.86','','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b','','','','yaml',''),
(16,'mall-member-prod.yaml','DEFAULT_GROUP','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n','75ca3ba047fe6ca4a12256fbd83055ea','2022-09-09 09:58:16','2023-12-27 00:12:41','nacos','10.0.0.86','','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b','','','','yaml',''),
(18,'mall-order-prod.yaml','DEFAULT_GROUP','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n\nmall:\n  thread:\n    core-size: 20\n    max-size: 100\n    keep-alive-time: 10','88c855ff2b506ed45c2188fe33d156b7','2022-09-09 12:46:16','2023-12-27 00:09:32','nacos','10.0.0.86','','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b','','','','yaml',''),
(20,'mall-search-prod.yaml','DEFAULT_GROUP','elasticsearch:\n  host: elasticsearch\n  port: 9200\n','d8953228c8d6c101ba193a84e43d510d','2022-09-09 22:49:31','2023-12-25 23:13:12','nacos','10.0.0.86','','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b','','','','yaml',''),
(21,'mall-third-party-prod.yaml','DEFAULT_GROUP','spring:\r\n  cloud:\r\n    alicloud:\r\n      access-key: keyXXXXXXXXXXXXXXXXXXXX\r\n      secret-key: keyXXXXXXXXX-XXXXXXXXXXX\r\n      oss:\r\n        endpoint: oss-cn-hangzhou.aliyuncs.com\r\n        bucket: gulimall-renchao\r\n      sms:\r\n        host: https://dfsns.market.alicloudapi.com\r\n        path: /data/send_sms\r\n        template-id: TPL_0000\r\n        appcode: b07d000000000000000000000047476c\r\n','65f9871e59200c693aa3b91ffab54524','2022-09-10 00:06:27','2022-09-10 00:06:27',NULL,'112.2.142.104','','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b',NULL,NULL,NULL,'yaml',NULL),
(26,'seataServer.properties','SEATA_GROUP','#Transaction routing rules configuration, only for the client\nservice.vgroupMapping.default_tx_group=default\n\n#Transaction storage configuration, only for the server. The file, db, and redis configuration values are optional.\nstore.mode=db\n\n#Used for password encryption\nstore.publicKey=\n\n#These configurations are required if the `store mode` is `db`. If `store.mode,store.lock.mode,store.session.mode` are not equal to `db`, you can remove the configuration block.\nstore.db.datasource=druid\nstore.db.dbType=mysql\nstore.db.driverClassName=com.mysql.cj.jdbc.Driver\nstore.db.url=jdbc:mysql://mysql:3306/seata?useUnicode=true&rewriteBatchedStatements=true\nstore.db.user=root\nstore.db.password=mall@111111\nstore.db.minConn=5\nstore.db.maxConn=30\nstore.db.globalTable=global_table\nstore.db.branchTable=branch_table\nstore.db.distributedLockTable=distributed_lock\nstore.db.queryLimit=100\nstore.db.lockTable=lock_table\nstore.db.maxWait=5000','e16d52a558d8c4ca28c96d49d98e5dce','2022-09-17 05:55:36','2023-12-27 12:33:29','nacos','10.0.0.86','','6a8ee0cb-25fa-42ea-8336-1c62a88751af','','','','properties',''),
(27,'mall-gateway-dev.yaml','DEFAULT_GROUP','spring:\n  cloud:\n    gateway:\n      routes:\n        - id: product_routh\n          uri: lb://mall-product\n          predicates:\n            - Path=/api/product/**\n          filters:\n            - RewritePath=/api/product(?<segment>/?.*), /product$\\{segment}\n\n        - id: member_routh\n          uri: lb://mall-member\n          predicates:\n            - Path=/api/member/**\n          filters:\n            - RewritePath=/api/member(?<segment>/?.*), /member$\\{segment}\n\n        - id: coupon_routh\n          uri: lb://mall-coupon\n          predicates:\n            - Path=/api/coupon/**\n          filters:\n            - RewritePath=/api/coupon(?<segment>/?.*), /coupon$\\{segment}\n\n        - id: ware_routh\n          uri: lb://mall-ware\n          predicates:\n            - Path=/api/ware/**\n          filters:\n            - RewritePath=/api/ware(?<segment>/?.*), /ware$\\{segment}\n\n        - id: third_party_routh\n          uri: lb://mall-third-party\n          predicates:\n            - Path=/api/thirdparty/**\n          filters:\n            - RewritePath=/api/thirdparty(?<segment>/?.*), $\\{segment}\n\n        - id: admin_routh\n          uri: lb://renren-fast\n          predicates:\n            - Path=/api/**\n          filters:\n            - RewritePath=/api(?<segment>/?.*), /renren-fast$\\{segment}\n\n        - id: mall_host_routh\n          uri: lb://mall-product\n          predicates:\n            - Host=renchao05.top,item.renchao05.top\n\n\n        - id: search_routh\n          uri: lb://mall-search\n          predicates:\n            - Host=search.renchao05.top\n\n        - id: auth_routh\n          uri: lb://mall-auth-server\n          predicates:\n            - Host=auth.renchao05.top\n\n        - id: cart_routh\n          uri: lb://mall-cart\n          predicates:\n            - Host=cart.renchao05.top\n\n        - id: order_routh\n          uri: lb://mall-order\n          predicates:\n            - Host=order.renchao05.top\n\n        - id: member_routh\n          uri: lb://mall-member\n          predicates:\n            - Host=member.renchao05.top\n\n        - id: seckill_routh\n          uri: lb://mall-seckill\n          predicates:\n            - Host=seckill.renchao05.top\n\n        - id: admin_fast_routh\n          uri: lb://renren-fast\n          predicates:\n            - Host=admin.renchao05.top','52aa29ff9fbf34d49a90825359ac3167','2022-09-18 14:51:43','2023-09-20 13:35:34','nacos','192.168.1.5','','54813a36-0a12-4f28-b0b7-ae91a6f032d8','','','','yaml',''),
(28,'common.yaml','DEFAULT_GROUP','server:\n  servlet:\n    session:\n      cookie:\n        name: GULISESSION\n        domain: renchao05.top\n\nspring:\n  cloud:\n    sentinel:\n      transport:\n        dashboard: sentinel:8088\n        port: 8719\n\n  zipkin:\n    base-url: http://zipkin:9411/\n    discoveryClientEnabled: false\n    sender:\n      type: web\n  sleuth:\n    sampler:\n      #采样率值介于 0 到 1 之间，1 则表示全部采集\n      probability: 1.0\n\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n\n  mvc:\n    date-format: yyyy-MM-dd HH:mm:ss\n\n\n  redis:\n    host: redis\n\n  # RabbitMQ 配置，其他的配置都有默认值\n  rabbitmq:\n    host: rabbitmq-service\n    username: mall\n    password: mall@111111\n    \n  # 配置缓存类型\n  cache:\n    type: redis\n    redis:\n      time-to-live: 360000\n      # 缓存空值\n      cache-null-values: true\n  # 分布式session配置\n  session:\n    store-type: redis\n\n\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n\nfeign:\n  sentinel:\n    enabled: true\n\n\nseata:\n  tx-service-group: default_tx_group\n  service:\n    vgroup-mapping:\n      default_tx_group: default\n  config:\n    type: nacos\n    nacos:\n      server-addr: nacos:8848\n      group : \"SEATA_GROUP\"\n      namespace: \"6a8ee0cb-25fa-42ea-8336-1c62a88751af\"\n      dataId: \"seataServer.properties\"\n  registry:\n    type: nacos\n    nacos:\n      application: seata-server\n      server-addr: nacos:8848\n      group : \"SEATA_GROUP\"\n      namespace: \"6a8ee0cb-25fa-42ea-8336-1c62a88751af\"\n','61b8c249e37e7c284943e899da70e608','2022-09-18 14:51:43','2023-10-25 23:47:19','nacos','10.244.0.0','','54813a36-0a12-4f28-b0b7-ae91a6f032d8','','','','yaml',''),
(29,'mall-product-dev.yaml','DEFAULT_GROUP','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: root\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n#      logic-delete-field: showStatus\n      logic-delete-value: 0\n      logic-not-delete-value: 1\n\n#logging:\n#  level:\n#    com.renchao.mall.product.dao: debug\n\nmall:\n  thread:\n    core-size: 20\n    max-size: 100\n    keep-alive-time: 10','b3283aa4420a3dfd504b2dae0eda9e55','2022-09-18 14:51:43','2023-10-25 00:02:53','nacos','10.244.0.0','','54813a36-0a12-4f28-b0b7-ae91a6f032d8','','','','yaml',''),
(30,'mall-auth-server-dev.yaml','DEFAULT_GROUP','#','01abfc750a0c942167651c40d088531d','2022-09-18 14:51:43','2022-09-18 14:51:43',NULL,'192.168.10.189','','54813a36-0a12-4f28-b0b7-ae91a6f032d8',NULL,NULL,NULL,'yaml',NULL),
(31,'mall-member-dev.yaml','DEFAULT_GROUP','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai\n    username: root\n    password: root\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto','605af9dbb730d69997cd1a275e4b7d5c','2022-09-18 14:51:43','2023-10-25 00:03:25','nacos','10.244.0.0','','54813a36-0a12-4f28-b0b7-ae91a6f032d8','','','','yaml',''),
(32,'mall-cart-dev.yaml','DEFAULT_GROUP','#','01abfc750a0c942167651c40d088531d','2022-09-18 14:51:43','2022-09-18 14:51:43',NULL,'192.168.10.189','','54813a36-0a12-4f28-b0b7-ae91a6f032d8',NULL,NULL,NULL,'yaml',NULL),
(33,'mall-order-dev.yaml','DEFAULT_GROUP','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: root\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n\n\nmall:\n  thread:\n    core-size: 20\n    max-size: 100\n    keep-alive-time: 10','db5401965883c4499ad7670d4d988ce2','2022-09-18 14:51:43','2023-10-25 00:04:11','nacos','10.244.0.0','','54813a36-0a12-4f28-b0b7-ae91a6f032d8','','','','yaml',''),
(34,'mall-ware-dev.yaml','DEFAULT_GROUP','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: root\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n\nlogging:\n  level:\n    com.renchao.mall.ware.dao: debug','d8dbbc127254a8a8834393ce2fb6f596','2022-09-18 14:51:43','2023-10-25 00:04:45','nacos','10.244.0.0','','54813a36-0a12-4f28-b0b7-ae91a6f032d8','','','','yaml',''),
(35,'mall-search-dev.yaml','DEFAULT_GROUP','elasticsearch:\n  host: elasticsearch-9200\n  port: 9200\n','bda5f951b45bddde17cf6bedb3e8eb3f','2022-09-18 14:51:43','2023-11-09 23:12:09','nacos','10.244.0.0','','54813a36-0a12-4f28-b0b7-ae91a6f032d8','','','','yaml',''),
(41,'mall-third-party-dev.yaml','DEFAULT_GROUP','spring:\r\n  cloud:\r\n    alicloud:\r\n      access-key: keyXXXXXXXXXXXXXXXXXXXX\r\n      secret-key: keyXXXXXXXXX-XXXXXXXXXXX\r\n      oss:\r\n        endpoint: oss-cn-hangzhou.aliyuncs.com\r\n        bucket: gulimall-renchao\r\n      sms:\r\n        host: https://dfsns.market.alicloudapi.com\r\n        path: /data/send_sms\r\n        template-id: TPL_0000\r\n        appcode: b07d000000000000000000000047476c\r\n','65f9871e59200c693aa3b91ffab54524','2022-09-19 02:13:50','2022-09-19 02:13:50',NULL,'192.168.10.189','','54813a36-0a12-4f28-b0b7-ae91a6f032d8',NULL,NULL,NULL,'yaml',NULL),
(42,'mall-coupon-dev.yaml','DEFAULT_GROUP','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: root\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto','b59398b9256845451bfb6bfd6277ebd8','2022-09-19 03:08:39','2023-10-25 14:33:34','nacos','10.244.0.0','','54813a36-0a12-4f28-b0b7-ae91a6f032d8','','','','yaml',''),
(81,'mall-admin-prod.yaml','DEFAULT_GROUP','spring:\n    datasource:\n        type: com.alibaba.druid.pool.DruidDataSource\n        druid:\n            driver-class-name: com.mysql.cj.jdbc.Driver\n            url: jdbc:mysql://mysql:3306/mall_admin?useUnicode=true&characterEncoding=UTF-8\n            username: root\n            password: mall@111111\n            initial-size: 10\n            max-active: 100\n            min-idle: 10\n            max-wait: 60000\n            pool-prepared-statements: true\n            max-pool-prepared-statement-per-connection-size: 20\n            time-between-eviction-runs-millis: 60000\n            min-evictable-idle-time-millis: 300000\n            #Oracle需要打开注释\n            #validation-query: SELECT 1 FROM DUAL\n            test-while-idle: true\n            test-on-borrow: false\n            test-on-return: false\n            stat-view-servlet:\n                enabled: true\n                url-pattern: /druid/*\n                #login-username: admin\n                #login-password: admin\n            filter:\n                stat:\n                    log-slow-sql: true\n                    slow-sql-millis: 1000\n                    merge-sql: false\n                wall:\n                    config:\n                        multi-statement-allow: true\n\n\n        sentinel:\n            transport:\n                dashboard: sentinel:8080 # 控制台地址\n                port: 8719\n\n    redis:\n        database: 0\n        host: redis\n        port: 6379\n        password: mall@111111    # 密码（默认为空）\n        timeout: 6000ms  # 连接超时时长（毫秒）\n        jedis:\n            pool:\n                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）\n                max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）\n                max-idle: 10      # 连接池中的最大空闲连接\n                min-idle: 5       # 连接池中的最小空闲连接\n','68bbabda4d745df191beed566ed7f53d','2023-12-27 08:44:26','2023-12-27 09:24:44','nacos','10.0.0.86','','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b','','','','yaml','');

/*Table structure for table `config_info_aggr` */

DROP TABLE IF EXISTS `config_info_aggr`;

CREATE TABLE `config_info_aggr` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfoaggr_datagrouptenantdatum` (`data_id`,`group_id`,`tenant_id`,`datum_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin COMMENT='增加租户字段';

/*Data for the table `config_info_aggr` */

/*Table structure for table `config_info_beta` */

DROP TABLE IF EXISTS `config_info_beta`;

CREATE TABLE `config_info_beta` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8mb3 COLLATE utf8mb3_bin COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfobeta_datagrouptenant` (`data_id`,`group_id`,`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin COMMENT='config_info_beta';

/*Data for the table `config_info_beta` */

/*Table structure for table `config_info_tag` */

DROP TABLE IF EXISTS `config_info_tag`;

CREATE TABLE `config_info_tag` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8mb3 COLLATE utf8mb3_bin COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfotag_datagrouptenanttag` (`data_id`,`group_id`,`tenant_id`,`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin COMMENT='config_info_tag';

/*Data for the table `config_info_tag` */

/*Table structure for table `config_tags_relation` */

DROP TABLE IF EXISTS `config_tags_relation`;

CREATE TABLE `config_tags_relation` (
  `id` bigint NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`),
  UNIQUE KEY `uk_configtagrelation_configidtag` (`id`,`tag_name`,`tag_type`),
  KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin COMMENT='config_tag_relation';

/*Data for the table `config_tags_relation` */

/*Table structure for table `group_capacity` */

DROP TABLE IF EXISTS `group_capacity`;

CREATE TABLE `group_capacity` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int unsigned NOT NULL DEFAULT '0' COMMENT '配额，0表示使用默认值',
  `usage` int unsigned NOT NULL DEFAULT '0' COMMENT '使用量',
  `max_size` int unsigned NOT NULL DEFAULT '0' COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int unsigned NOT NULL DEFAULT '0' COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int unsigned NOT NULL DEFAULT '0' COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int unsigned NOT NULL DEFAULT '0' COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_group_id` (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin COMMENT='集群、各Group容量信息表';

/*Data for the table `group_capacity` */

/*Table structure for table `his_config_info` */

DROP TABLE IF EXISTS `his_config_info`;

CREATE TABLE `his_config_info` (
  `id` bigint unsigned NOT NULL,
  `nid` bigint unsigned NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `src_user` text CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `src_ip` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`nid`),
  KEY `idx_gmt_create` (`gmt_create`),
  KEY `idx_gmt_modified` (`gmt_modified`),
  KEY `idx_did` (`data_id`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin COMMENT='多租户改造';

/*Data for the table `his_config_info` */

insert  into `his_config_info`(`id`,`nid`,`data_id`,`group_id`,`app_name`,`content`,`md5`,`gmt_create`,`gmt_modified`,`src_user`,`src_ip`,`op_type`,`tenant_id`) values 
(2,25,'common.yaml','DEFAULT_GROUP','','server:\n  servlet:\n    session:\n      cookie:\n        name: GULISESSION\n        domain: renchao05.top\n\nspring:\n  cloud:\n    sentinel:\n      transport:\n        dashboard: sentinel.mall.renchao05.top:8088\n        port: 8719\n\n  zipkin:\n    base-url: http://zipkin.mall.renchao05.top:9411/\n    discoveryClientEnabled: false\n    sender:\n      type: web\n  sleuth:\n    sampler:\n      #采样率值介于 0 到 1 之间，1 则表示全部采集\n      probability: 1.0\n\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n\n  mvc:\n    date-format: yyyy-MM-dd HH:mm:ss\n\n\n  redis:\n    host: redis.mall.renchao05.top\n    password: mall@111111\n  # RabbitMQ 配置，其他的配置都有默认值\n  rabbitmq:\n    host: rabbitmq.mall.renchao05.top\n    password: mall@111111\n    \n  # 配置缓存类型\n  cache:\n    type: redis\n    redis:\n      time-to-live: 360000\n      # 缓存空值\n      cache-null-values: true\n  # 分布式session配置\n  session:\n    store-type: redis\n\n\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n\nfeign:\n  sentinel:\n    enabled: true','b110259c00e296d6ffecedc425e6018b','2023-12-25 22:52:23','2023-12-25 22:52:24','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(3,26,'mall-gateway-prod.yaml','DEFAULT_GROUP','','spring:\n  cloud:\n    gateway:\n      routes:\n        - id: product_routh\n          uri: lb://gulimall-product\n          predicates:\n            - Path=/api/product/**\n          filters:\n            - RewritePath=/api/product(?<segment>/?.*), /product$\\{segment}\n\n        - id: member_routh\n          uri: lb://gulimall-member\n          predicates:\n            - Path=/api/member/**\n          filters:\n            - RewritePath=/api/member(?<segment>/?.*), /member$\\{segment}\n\n        - id: coupon_routh\n          uri: lb://gulimall-coupon\n          predicates:\n            - Path=/api/coupon/**\n          filters:\n            - RewritePath=/api/coupon(?<segment>/?.*), /coupon$\\{segment}\n\n        - id: ware_routh\n          uri: lb://gulimall-ware\n          predicates:\n            - Path=/api/ware/**\n          filters:\n            - RewritePath=/api/ware(?<segment>/?.*), /ware$\\{segment}\n\n        - id: third_party_routh\n          uri: lb://gulimall-third-party\n          predicates:\n            - Path=/api/thirdparty/**\n          filters:\n            - RewritePath=/api/thirdparty(?<segment>/?.*), $\\{segment}\n\n        - id: admin_routh\n          uri: lb://renren-fast\n          predicates:\n            - Path=/api/**\n          filters:\n            - RewritePath=/api(?<segment>/?.*), /renren-fast$\\{segment}\n\n        - id: gulimall_host_routh\n          uri: lb://gulimall-product\n          predicates:\n            - Host=renchao05.top,item.renchao05.top\n\n\n        - id: search_routh\n          uri: lb://gulimall-search\n          predicates:\n            - Host=search.renchao05.top\n\n        - id: auth_routh\n          uri: lb://gulimall-auth-server\n          predicates:\n            - Host=auth.renchao05.top\n\n        - id: cart_routh\n          uri: lb://gulimall-cart\n          predicates:\n            - Host=cart.renchao05.top\n\n        - id: order_routh\n          uri: lb://gulimall-order\n          predicates:\n            - Host=order.renchao05.top\n\n        - id: member_routh\n          uri: lb://gulimall-member\n          predicates:\n            - Host=member.renchao05.top\n\n        - id: seckill_routh\n          uri: lb://gulimall-seckill\n          predicates:\n            - Host=seckill.renchao05.top\n\n        - id: admin_fast_routh\n          uri: lb://renren-fast\n          predicates:\n            - Host=admin.renchao05.top','76f73ad34f57dd062f6df3fbe1988332','2023-12-25 22:53:48','2023-12-25 22:53:48','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(5,27,'mall-product-prod.yaml','DEFAULT_GROUP','','spring:\n  application:\n    name: gulimall-product\n\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://sql.mall.renchao05.top:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n#      logic-delete-field: showStatus\n      logic-delete-value: 0\n      logic-not-delete-value: 1\n\n#logging:\n#  level:\n#    com.renchao.gulimall.product.dao: debug\n\ngulimall:\n  thread:\n    core-size: 20\n    max-size: 100\n    keep-alive-time: 10','40706dc406dde951eb5ca73b93c05787','2023-12-25 23:07:55','2023-12-25 23:07:56','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(9,28,'mall-ware-prod.yaml','DEFAULT_GROUP','','spring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    #MySQL配置\r\n    driverClassName: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://sql.mall.renchao05.top:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai\r\n    username: root\r\n    password: mall@111111\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:/mapper/**/*.xml\r\n  global-config:\r\n    db-config:\r\n      # 主键自增\r\n      id-type: auto','4218d15058827d0339035819c6d4a006','2023-12-25 23:08:41','2023-12-25 23:08:42','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(13,29,'mall.com-prod.yaml','DEFAULT_GROUP','','#','01abfc750a0c942167651c40d088531d','2023-12-25 23:10:17','2023-12-25 23:10:18',NULL,'10.0.0.86','D','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(14,30,'mall-coupon-prod.yaml','DEFAULT_GROUP','','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://sql.mall.renchao05.top/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto','4ca3365996eb82599d935f012039dfa6','2023-12-25 23:10:37','2023-12-25 23:10:38','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(16,31,'mall-member-prod.yaml','DEFAULT_GROUP','','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://sql.mall.renchao05.top:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n','8c80cd92da73d9d82673cb8101d7cbd8','2023-12-25 23:11:10','2023-12-25 23:11:10','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(14,32,'mall-coupon-prod.yaml','DEFAULT_GROUP','','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto','fd5ee3dc22d8a5bc8b4e17f4b35bd36c','2023-12-25 23:12:00','2023-12-25 23:12:01','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(18,33,'mall-order-prod.yaml','DEFAULT_GROUP','','spring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    #MySQL配置\r\n    driverClassName: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://sql.mall.renchao05.top:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\r\n    username: root\r\n    password: mall@111111\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:/mapper/**/*.xml\r\n  global-config:\r\n    db-config:\r\n      # 主键自增\r\n      id-type: auto\r\n\r\ngulimall:\r\n  thread:\r\n    core-size: 20\r\n    max-size: 100\r\n    keep-alive-time: 10','58f621af1ea9602df3c6a2d5574eb5b8','2023-12-25 23:12:37','2023-12-25 23:12:37','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(20,34,'mall-search-prod.yaml','DEFAULT_GROUP','','elasticsearch:\r\n  host: es.mall.renchao05.top\r\n  port: 9200\r\n','2a147f9e528716f474c77010bb9e3969','2023-12-25 23:13:12','2023-12-25 23:13:12','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(2,35,'common.yaml','DEFAULT_GROUP','','server:\n  servlet:\n    session:\n      cookie:\n        name: GULISESSION\n        domain: renchao05.top\n\nspring:\n  cloud:\n    sentinel:\n      transport:\n        dashboard: sentinel:8080\n        port: 8719\n\n  zipkin:\n    base-url: http://zipkin:9411/\n    discoveryClientEnabled: false\n    sender:\n      type: web\n  sleuth:\n    sampler:\n      #采样率值介于 0 到 1 之间，1 则表示全部采集\n      probability: 1.0\n\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n\n  mvc:\n    date-format: yyyy-MM-dd HH:mm:ss\n\n\n  redis:\n    host: redis\n    password: mall@111111\n  # RabbitMQ 配置，其他的配置都有默认值\n  rabbitmq:\n    host: rabbitmq\n    password: mall@111111\n    \n  # 配置缓存类型\n  cache:\n    type: redis\n    redis:\n      time-to-live: 360000\n      # 缓存空值\n      cache-null-values: true\n  # 分布式session配置\n  session:\n    store-type: redis\n\n\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n\nfeign:\n  sentinel:\n    enabled: true','9d63f4bd3ec78753cc1e3cff52df519a','2023-12-26 23:56:03','2023-12-26 23:56:03','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(5,36,'mall-product-prod.yaml','DEFAULT_GROUP','','spring:\n  application:\n    name: mall-product\n\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n#      logic-delete-field: showStatus\n      logic-delete-value: 0\n      logic-not-delete-value: 1\n\n#logging:\n#  level:\n#    com.renchao.gulimall.product.dao: debug\n\ngulimall:\n  thread:\n    core-size: 20\n    max-size: 100\n    keep-alive-time: 10','032eaa1f7dff8dc8bef2a246857ace52','2023-12-26 23:56:55','2023-12-26 23:56:55','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(9,37,'mall-ware-prod.yaml','DEFAULT_GROUP','','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto','62d5c2e90fd19a3ecf30066359b9e92e','2023-12-26 23:57:18','2023-12-26 23:57:19','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(14,38,'mall-coupon-prod.yaml','DEFAULT_GROUP','','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto','a5b0dd462f6cc2c442ea90f6c72b5112','2023-12-26 23:57:43','2023-12-26 23:57:43','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(14,39,'mall-coupon-prod.yaml','DEFAULT_GROUP','','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto','57f6c1d4a5e5ddb8c201a1cf4d0fe65b','2023-12-26 23:58:40','2023-12-26 23:58:40','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(16,40,'mall-member-prod.yaml','DEFAULT_GROUP','','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n','afdc2e47726f1e37d4cc462715e4aa4a','2023-12-26 23:59:02','2023-12-26 23:59:02','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(18,41,'mall-order-prod.yaml','DEFAULT_GROUP','','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n\ngulimall:\n  thread:\n    core-size: 20\n    max-size: 100\n    keep-alive-time: 10','856f14517723c46a97376221152404e8','2023-12-26 23:59:19','2023-12-26 23:59:20','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(18,42,'mall-order-prod.yaml','DEFAULT_GROUP','','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n\ngulimall:\n  thread:\n    core-size: 20\n    max-size: 100\n    keep-alive-time: 10','afc7b40d12e19ac9b41b7f3fb0f48585','2023-12-27 00:04:14','2023-12-27 00:04:15','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(18,43,'mall-order-prod.yaml','DEFAULT_GROUP','','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n\ngulimall:\n  thread:\n    core-size: 20\n    max-size: 100\n    keep-alive-time: 10','6d23db751976e9daf5c19700106fd47c','2023-12-27 00:09:32','2023-12-27 00:09:32','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(3,44,'mall-gateway-prod.yaml','DEFAULT_GROUP','','spring:\n  cloud:\n    gateway:\n      routes:\n        - id: product_routh\n          uri: lb://mall-product\n          predicates:\n            - Path=/api/product/**\n          filters:\n            - RewritePath=/api/product(?<segment>/?.*), /product$\\{segment}\n\n        - id: member_routh\n          uri: lb://mall-member\n          predicates:\n            - Path=/api/member/**\n          filters:\n            - RewritePath=/api/member(?<segment>/?.*), /member$\\{segment}\n\n        - id: coupon_routh\n          uri: lb://mall-coupon\n          predicates:\n            - Path=/api/coupon/**\n          filters:\n            - RewritePath=/api/coupon(?<segment>/?.*), /coupon$\\{segment}\n\n        - id: ware_routh\n          uri: lb://mall-ware\n          predicates:\n            - Path=/api/ware/**\n          filters:\n            - RewritePath=/api/ware(?<segment>/?.*), /ware$\\{segment}\n\n        - id: third_party_routh\n          uri: lb://mall-third-party\n          predicates:\n            - Path=/api/thirdparty/**\n          filters:\n            - RewritePath=/api/thirdparty(?<segment>/?.*), $\\{segment}\n\n        - id: admin_routh\n          uri: lb://renren-fast\n          predicates:\n            - Path=/api/**\n          filters:\n            - RewritePath=/api(?<segment>/?.*), /renren-fast$\\{segment}\n\n        - id: gulimall_host_routh\n          uri: lb://mall-product\n          predicates:\n            - Host=renchao05.top,item.renchao05.top\n\n\n        - id: search_routh\n          uri: lb://mall-search\n          predicates:\n            - Host=search.renchao05.top\n\n        - id: auth_routh\n          uri: lb://mall-auth-server\n          predicates:\n            - Host=auth.renchao05.top\n\n        - id: cart_routh\n          uri: lb://mall-cart\n          predicates:\n            - Host=cart.renchao05.top\n\n        - id: order_routh\n          uri: lb://mall-order\n          predicates:\n            - Host=order.renchao05.top\n\n        - id: member_routh\n          uri: lb://mall-member\n          predicates:\n            - Host=member.renchao05.top\n\n        - id: seckill_routh\n          uri: lb://mall-seckill\n          predicates:\n            - Host=seckill.renchao05.top\n\n        - id: admin_fast_routh\n          uri: lb://renren-fast\n          predicates:\n            - Host=admin.renchao05.top','b75fe22ab00db4b4a7f16bda397ba725','2023-12-27 00:10:33','2023-12-27 00:10:34','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(5,45,'mall-product-prod.yaml','DEFAULT_GROUP','','spring:\n  application:\n    name: mall-product\n\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n#      logic-delete-field: showStatus\n      logic-delete-value: 0\n      logic-not-delete-value: 1\n\n#logging:\n#  level:\n#    com.renchao.gulimall.product.dao: debug\n\ngulimall:\n  thread:\n    core-size: 20\n    max-size: 100\n    keep-alive-time: 10','94c4d0370c35add0d3b86224870753f4','2023-12-27 00:11:10','2023-12-27 00:11:11','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(5,46,'mall-product-prod.yaml','DEFAULT_GROUP','','spring:\n  application:\n    name: mall-product\n\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n#      logic-delete-field: showStatus\n      logic-delete-value: 0\n      logic-not-delete-value: 1\n\n#logging:\n#  level:\n#    com.renchao.gulimall.product.dao: debug\n\nmall:\n  thread:\n    core-size: 20\n    max-size: 100\n    keep-alive-time: 10','b1fcdbfc8bbfe6a712d6ceb3d62b2adf','2023-12-27 00:11:30','2023-12-27 00:11:30','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(14,47,'mall-coupon-prod.yaml','DEFAULT_GROUP','','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto','57f6c1d4a5e5ddb8c201a1cf4d0fe65b','2023-12-27 00:12:18','2023-12-27 00:12:18','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(16,48,'mall-member-prod.yaml','DEFAULT_GROUP','','spring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    #MySQL配置\n    driverClassName: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://mysql:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false\n    username: root\n    password: mall@111111\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  global-config:\n    db-config:\n      # 主键自增\n      id-type: auto\n','d349e07e9ac9bab009b636d21adb8291','2023-12-27 00:12:41','2023-12-27 00:12:41','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(2,49,'common.yaml','DEFAULT_GROUP','','server:\n  servlet:\n    session:\n      cookie:\n        name: GULISESSION\n        domain: renchao05.top\n\nspring:\n  cloud:\n    sentinel:\n      transport:\n        dashboard: sentinel:8080\n        port: 8719\n\n  zipkin:\n    base-url: http://zipkin:9411/\n    discoveryClientEnabled: false\n    sender:\n      type: web\n  sleuth:\n    sampler:\n      #采样率值介于 0 到 1 之间，1 则表示全部采集\n      probability: 1.0\n\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n\n  mvc:\n    date-format: yyyy-MM-dd HH:mm:ss\n\n\n  redis:\n    host: redis\n    password: mall@111111\n  # RabbitMQ 配置，其他的配置都有默认值\n  rabbitmq:\n    host: rabbitmq\n    password: mall@111111\n    \n  # 配置缓存类型\n  cache:\n    type: redis\n    redis:\n      time-to-live: 360000\n      # 缓存空值\n      cache-null-values: true\n  # 分布式session配置\n  session:\n    store-type: redis\n\n\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n\nfeign:\n  sentinel:\n    enabled: true','6764d0df5afaf9a57deb1b3972d07036','2023-12-27 05:42:05','2023-12-27 05:42:05','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(0,50,'mall-admin-prod.yaml','DEFAULT_GROUP','','spring:\r\n    datasource:\r\n        type: com.alibaba.druid.pool.DruidDataSource\r\n        druid:\r\n            driver-class-name: com.mysql.cj.jdbc.Driver\r\n            url: jdbc:mysql://mysql:3306/mall_admin?useUnicode=true&characterEncoding=UTF-8\r\n            username: root\r\n            password: mall@111111\r\n            initial-size: 10\r\n            max-active: 100\r\n            min-idle: 10\r\n            max-wait: 60000\r\n            pool-prepared-statements: true\r\n            max-pool-prepared-statement-per-connection-size: 20\r\n            time-between-eviction-runs-millis: 60000\r\n            min-evictable-idle-time-millis: 300000\r\n            #Oracle需要打开注释\r\n            #validation-query: SELECT 1 FROM DUAL\r\n            test-while-idle: true\r\n            test-on-borrow: false\r\n            test-on-return: false\r\n            stat-view-servlet:\r\n                enabled: true\r\n                url-pattern: /druid/*\r\n                #login-username: admin\r\n                #login-password: admin\r\n            filter:\r\n                stat:\r\n                    log-slow-sql: true\r\n                    slow-sql-millis: 1000\r\n                    merge-sql: false\r\n                wall:\r\n                    config:\r\n                        multi-statement-allow: true\r\n\r\n    cloud:\r\n        nacos:\r\n            discovery:\r\n                server-addr: nacos:8848 #配置Nacos地址\r\n        #  resources:\r\n        #    add-mappings: false\r\n        sentinel:\r\n            transport:\r\n                dashboard: sentinel:8080 # 控制台地址\r\n                port: 8719\r\n\r\n    redis:\r\n        database: 0\r\n        host: redis\r\n        port: 6379\r\n        password: mall@111111    # 密码（默认为空）\r\n        timeout: 6000ms  # 连接超时时长（毫秒）\r\n        jedis:\r\n            pool:\r\n                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）\r\n                max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）\r\n                max-idle: 10      # 连接池中的最大空闲连接\r\n                min-idle: 5       # 连接池中的最小空闲连接\r\n##多数据源的配置\r\n#dynamic:\r\n#  datasource:\r\n#    slave1:\r\n#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver\r\n#      url: jdbc:sqlserver://localhost:1433;DatabaseName=renren_security\r\n#      username: sa\r\n#      password: 123456\r\n#    slave2:\r\n#      driver-class-name: org.postgresql.Driver\r\n#      url: jdbc:postgresql://localhost:5432/renren_security\r\n#      username: renren\r\n#      password: 123456','117b912e58d169a720bcdcdcc12cced0','2023-12-27 08:44:25','2023-12-27 08:44:26',NULL,'10.0.0.86','I','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(81,51,'mall-admin-prod.yaml','DEFAULT_GROUP','','spring:\r\n    datasource:\r\n        type: com.alibaba.druid.pool.DruidDataSource\r\n        druid:\r\n            driver-class-name: com.mysql.cj.jdbc.Driver\r\n            url: jdbc:mysql://mysql:3306/mall_admin?useUnicode=true&characterEncoding=UTF-8\r\n            username: root\r\n            password: mall@111111\r\n            initial-size: 10\r\n            max-active: 100\r\n            min-idle: 10\r\n            max-wait: 60000\r\n            pool-prepared-statements: true\r\n            max-pool-prepared-statement-per-connection-size: 20\r\n            time-between-eviction-runs-millis: 60000\r\n            min-evictable-idle-time-millis: 300000\r\n            #Oracle需要打开注释\r\n            #validation-query: SELECT 1 FROM DUAL\r\n            test-while-idle: true\r\n            test-on-borrow: false\r\n            test-on-return: false\r\n            stat-view-servlet:\r\n                enabled: true\r\n                url-pattern: /druid/*\r\n                #login-username: admin\r\n                #login-password: admin\r\n            filter:\r\n                stat:\r\n                    log-slow-sql: true\r\n                    slow-sql-millis: 1000\r\n                    merge-sql: false\r\n                wall:\r\n                    config:\r\n                        multi-statement-allow: true\r\n\r\n    cloud:\r\n        nacos:\r\n            discovery:\r\n                server-addr: nacos:8848 #配置Nacos地址\r\n        #  resources:\r\n        #    add-mappings: false\r\n        sentinel:\r\n            transport:\r\n                dashboard: sentinel:8080 # 控制台地址\r\n                port: 8719\r\n\r\n    redis:\r\n        database: 0\r\n        host: redis\r\n        port: 6379\r\n        password: mall@111111    # 密码（默认为空）\r\n        timeout: 6000ms  # 连接超时时长（毫秒）\r\n        jedis:\r\n            pool:\r\n                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）\r\n                max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）\r\n                max-idle: 10      # 连接池中的最大空闲连接\r\n                min-idle: 5       # 连接池中的最小空闲连接\r\n##多数据源的配置\r\n#dynamic:\r\n#  datasource:\r\n#    slave1:\r\n#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver\r\n#      url: jdbc:sqlserver://localhost:1433;DatabaseName=renren_security\r\n#      username: sa\r\n#      password: 123456\r\n#    slave2:\r\n#      driver-class-name: org.postgresql.Driver\r\n#      url: jdbc:postgresql://localhost:5432/renren_security\r\n#      username: renren\r\n#      password: 123456','117b912e58d169a720bcdcdcc12cced0','2023-12-27 09:24:44','2023-12-27 09:24:44','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(26,52,'seataServer.properties','SEATA_GROUP','','#Transaction routing rules configuration, only for the client\nservice.vgroupMapping.default_tx_group=default\n\n#Transaction storage configuration, only for the server. The file, db, and redis configuration values are optional.\nstore.mode=db\n\n#Used for password encryption\nstore.publicKey=\n\n#These configurations are required if the `store mode` is `db`. If `store.mode,store.lock.mode,store.session.mode` are not equal to `db`, you can remove the configuration block.\nstore.db.datasource=druid\nstore.db.dbType=mysql\nstore.db.driverClassName=com.mysql.cj.jdbc.Driver\nstore.db.url=jdbc:mysql://mysql:3306/seata?useUnicode=true&rewriteBatchedStatements=true\nstore.db.user=root\nstore.db.password=root\nstore.db.minConn=5\nstore.db.maxConn=30\nstore.db.globalTable=global_table\nstore.db.branchTable=branch_table\nstore.db.distributedLockTable=distributed_lock\nstore.db.queryLimit=100\nstore.db.lockTable=lock_table\nstore.db.maxWait=5000','ebda92040f04fbcaef2f91b3a4b1d470','2023-12-27 12:33:28','2023-12-27 12:33:29','nacos','10.0.0.86','U','6a8ee0cb-25fa-42ea-8336-1c62a88751af'),
(2,53,'common.yaml','DEFAULT_GROUP','','server:\n  servlet:\n    session:\n      cookie:\n        name: GULISESSION\n        domain: renchao05.top\n\nspring:\n  cloud:\n    sentinel:\n      transport:\n        dashboard: sentinel:8080\n        port: 8719\n\n  zipkin:\n    base-url: http://zipkin:9411/\n    discoveryClientEnabled: false\n    sender:\n      type: web\n  sleuth:\n    sampler:\n      #采样率值介于 0 到 1 之间，1 则表示全部采集\n      probability: 1.0\n\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n\n  mvc:\n    date-format: yyyy-MM-dd HH:mm:ss\n\n\n  redis:\n    host: redis\n    password: mall@111111\n  # RabbitMQ 配置，其他的配置都有默认值\n  rabbitmq:\n    host: rabbitmq\n    username: mall\n    password: mall@111111\n    \n  # 配置缓存类型\n  cache:\n    type: redis\n    redis:\n      time-to-live: 360000\n      # 缓存空值\n      cache-null-values: true\n  # 分布式session配置\n  session:\n    store-type: redis\n\n\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n\nfeign:\n  sentinel:\n    enabled: true','5d1100b767e42844dceb9acf5f7fcbe2','2023-12-27 12:40:12','2023-12-27 12:40:13','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b'),
(3,54,'mall-gateway-prod.yaml','DEFAULT_GROUP','','spring:\n  cloud:\n    gateway:\n      routes:\n        - id: product_routh\n          uri: lb://mall-product\n          predicates:\n            - Path=/api/product/**\n          filters:\n            - RewritePath=/api/product(?<segment>/?.*), /product$\\{segment}\n\n        - id: member_routh\n          uri: lb://mall-member\n          predicates:\n            - Path=/api/member/**\n          filters:\n            - RewritePath=/api/member(?<segment>/?.*), /member$\\{segment}\n\n        - id: coupon_routh\n          uri: lb://mall-coupon\n          predicates:\n            - Path=/api/coupon/**\n          filters:\n            - RewritePath=/api/coupon(?<segment>/?.*), /coupon$\\{segment}\n\n        - id: ware_routh\n          uri: lb://mall-ware\n          predicates:\n            - Path=/api/ware/**\n          filters:\n            - RewritePath=/api/ware(?<segment>/?.*), /ware$\\{segment}\n\n        - id: third_party_routh\n          uri: lb://mall-third-party\n          predicates:\n            - Path=/api/thirdparty/**\n          filters:\n            - RewritePath=/api/thirdparty(?<segment>/?.*), $\\{segment}\n\n        - id: admin_routh\n          uri: lb://renren-fast\n          predicates:\n            - Path=/api/**\n          filters:\n            - RewritePath=/api(?<segment>/?.*), /renren-fast$\\{segment}\n\n        - id: mall_host_routh\n          uri: lb://mall-product\n          predicates:\n            - Host=renchao05.top,item.renchao05.top\n\n\n        - id: search_routh\n          uri: lb://mall-search\n          predicates:\n            - Host=search.renchao05.top\n\n        - id: auth_routh\n          uri: lb://mall-auth-server\n          predicates:\n            - Host=auth.renchao05.top\n\n        - id: cart_routh\n          uri: lb://mall-cart\n          predicates:\n            - Host=cart.renchao05.top\n\n        - id: order_routh\n          uri: lb://mall-order\n          predicates:\n            - Host=order.renchao05.top\n\n        - id: member_routh\n          uri: lb://mall-member\n          predicates:\n            - Host=member.renchao05.top\n\n        - id: seckill_routh\n          uri: lb://mall-seckill\n          predicates:\n            - Host=seckill.renchao05.top\n\n        - id: admin_fast_routh\n          uri: lb://renren-fast\n          predicates:\n            - Host=admin.renchao05.top','52aa29ff9fbf34d49a90825359ac3167','2023-12-28 23:24:25','2023-12-28 23:24:25','nacos','10.0.0.86','U','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b');

/*Table structure for table `permissions` */

DROP TABLE IF EXISTS `permissions`;

CREATE TABLE `permissions` (
  `role` varchar(50) NOT NULL,
  `resource` varchar(255) NOT NULL,
  `action` varchar(8) NOT NULL,
  UNIQUE KEY `uk_role_permission` (`role`,`resource`,`action`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `permissions` */

/*Table structure for table `roles` */

DROP TABLE IF EXISTS `roles`;

CREATE TABLE `roles` (
  `username` varchar(50) NOT NULL,
  `role` varchar(50) NOT NULL,
  UNIQUE KEY `idx_user_role` (`username`,`role`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `roles` */

insert  into `roles`(`username`,`role`) values 
('nacos','ROLE_ADMIN');

/*Table structure for table `tenant_capacity` */

DROP TABLE IF EXISTS `tenant_capacity`;

CREATE TABLE `tenant_capacity` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int unsigned NOT NULL DEFAULT '0' COMMENT '配额，0表示使用默认值',
  `usage` int unsigned NOT NULL DEFAULT '0' COMMENT '使用量',
  `max_size` int unsigned NOT NULL DEFAULT '0' COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int unsigned NOT NULL DEFAULT '0' COMMENT '聚合子配置最大个数',
  `max_aggr_size` int unsigned NOT NULL DEFAULT '0' COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int unsigned NOT NULL DEFAULT '0' COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin COMMENT='租户容量信息表';

/*Data for the table `tenant_capacity` */

/*Table structure for table `tenant_info` */

DROP TABLE IF EXISTS `tenant_info`;

CREATE TABLE `tenant_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_info_kptenantid` (`kp`,`tenant_id`),
  KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin COMMENT='tenant_info';

/*Data for the table `tenant_info` */

insert  into `tenant_info`(`id`,`kp`,`tenant_id`,`tenant_name`,`tenant_desc`,`create_source`,`gmt_create`,`gmt_modified`) values 
(1,'1','d8f325dd-27fa-4cd7-8fe6-efe2ebaf711b','prod','产品环境','nacos',1662638210936,1662638210936),
(2,'1','6a8ee0cb-25fa-42ea-8336-1c62a88751af','seata','seata','nacos',1663368367024,1663368367024),
(3,'1','54813a36-0a12-4f28-b0b7-ae91a6f032d8','test','test','nacos',1663512596611,1699574419245);

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `username` varchar(50) NOT NULL,
  `password` varchar(500) NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `users` */

insert  into `users`(`username`,`password`,`enabled`) values 
('nacos','$2a$10$j68/AqnjykdNNEqiRKyhiezRsj8Ca.enPCupUyFFQI2BBNyrrLWDa',1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
